apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-app
  namespace: argocd
spec:
  project: default
  source:
<<<<<<< HEAD
    repoURL: https://github.com/rahulsingh12112/argocd-lab1.git
=======
    repoURL: https://github.com/rahulsingh12112/helm-lab
>>>>>>> 7b54378 (add app-of-apps parent + app manifests)
    targetRevision: main
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    syncOptions:
<<<<<<< HEAD
      - CreateNamespace=true
=======
     - CreateNamespace=true
    automated:
      prune:  true
      selfHeal: true
>>>>>>> 7b54378 (add app-of-apps parent + app manifests)
