apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hello-git-appset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/rahulsingh12112/helm-lab.git
        revision: main
        directories:
          - path: envs/*
  template:
    metadata:
      name: 'gitgen-{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/rahulsingh12112/helm-lab.git
        targetRevision: main
        path: .
      destination:
        server: https://kubernetes.default.svc
        namespace: 'gitgen-{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true