apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hello-appset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: dev
          - env: qa
          - env: uat
          - env: prod
  template:
    metadata:
      name: 'appset-{{env}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/rahulsingh12112/helm-lab.git
        targetRevision: main
        path: .
        helm:
          valueFiles:
            - 'envs/{{env}}/values.yaml'
      destination:
        server: https://kubernetes.default.svc
        namespace: 'appset-{{env}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
